server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Angular routing
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Redirige llamadas /api hacia el BFF desplegado en la misma EC2
    location /api/ {
        proxy_pass http://44.205.171.7:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}