server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Angular routing
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Las llamadas /api se resuelven en el Nginx principal de la EC2.
    # Este contenedor solo sirve los archivos estaticos de Angular.
}
